url:
  root: https://www.finnomena.com
  fund: /fund
  fund_timeseries_price: https://www.finnomena.com/fn3/api/fund/nav/q


fees_dict:
  ค่าธรรมเนียมการขายหน่วยลงทุน (Front-end Fee): purchase fee
  ค่าธรรมเนียมการจัดการ: management fee
  ค่าธรรมเนียมการรับซื้อคืนหน่วยลงทุน (Back-end Fee): redemption fee
  ค่าธรรมเนียมการสับเปลี่ยนหน่วยลงทุนเข้า (SWITCHING IN): switching-in fee
  ค่าธรรมเนียมการสับเปลี่ยนหน่วยลงทุนออก (SWITCHING OUT): switching-out fee
  ค่าธรรมเนียมและค่าใช้จ่ายรวมทั้งหมด: total expense ratio